[workspace]
resolver = "2"

members = [
  "dense",
  "operator",
  "sparse",
  "common",
  "io",
  "suitesparse-src",
  "blis-src",
  "umfpack",
  "gfortran-src",
  "netlib-lapack-src",
  "blis",
  "rlst",
  "proc-macro",
]
