name: 🧪 Test

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 7 * * 1"

jobs:
  run-tests:
    name: Run tests (Rust)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust-version: ["stable", "beta", "nightly"]
        mpi: [ 'libmpich-dev', 'libopenmpi-dev' ]
    steps:
      - name: Install compilers and MPI
        run: sudo apt-get install -y llvm-dev libclang-dev pkgconf ${{ matrix.mpi }}
      - name: Install LAPACK & OpenBLAS
        run: sudo apt-get install -y libopenblas-dev liblapack-dev libclang-15-dev

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust-version }}
          components: rustfmt
      - name: Install cargo-mpirun
        run: cargo install cargo-mpirun

      - uses: actions/checkout@v3

      - name: Style checks
        run: cargo fmt -- --check

      - name: Build rust library (debug)
        run: cargo build --features "strict,mpi"
      - name: Build rust library (release)
        run: cargo build --release --features "strict,mpi"

      - name: Run unit tests
        run: cargo test --lib --features "mpi,strict"
      - name: Run tests
        run: cargo test --examples --release --features "mpi,strict"
      - name: Run examples
        run: |
          python3 find_examples.py
          chmod +x examples.sh
          ./examples.sh

      - name: Build docs
        run: cargo doc --features "mpi,strict"
